from taichi.math import vec2, vec3, vec4, ivec2, ivec3, ivec4

ATOM = 'CaII'
ELEMENT = 'Ca'
LINEIDX = 0

#The cloned package path
TRACER_ROOT = "your/path/here"

if ELEMENT == 'Ca':
    ION_I0 = 9
    ION_I1 = 15

if ELEMENT == 'Mg':
    ION_I0 = 9
    ION_I1 = 20

TRANSFER_CENTRE_VAL = 4
TRANSFER_CENTRE_WIDTH = 0.1
TRANSFER_BASE_COLOR = vec3(0.8, 0.0, 0.8) * 0.1
USE_HDDA = False
USE_MSAA = True

#TRACER SETUP
CAM_HEIGHT = 640
CAM_ASPECT = 16 / 9
CAM_WIDTH = int(CAM_ASPECT * CAM_HEIGHT)
CAM_SIZE = (CAM_HEIGHT*CAM_ASPECT, CAM_HEIGHT)

#GUI SETUP
VERTICAL_PAD = 10
RIGHT_PAD = 200 #space for the sliders
SPEC_WIDTH = 120 #panel width
VIEWER_HEIGHT = 640
VIEWER_WIDTH = VIEWER_HEIGHT * CAM_ASPECT
VIEWER_SIZE = (VIEWER_WIDTH, VIEWER_HEIGHT)

WINDOW_SIZE = (int(SPEC_WIDTH + VIEWER_WIDTH + RIGHT_PAD), int(VIEWER_HEIGHT + VERTICAL_PAD*2))
VIEWER_AABB = (int(SPEC_WIDTH), int(VERTICAL_PAD), int(SPEC_WIDTH+VIEWER_WIDTH), int(VERTICAL_PAD+VIEWER_HEIGHT))

MAIN_AABB = ivec4(0,0,WINDOW_SIZE[0],WINDOW_SIZE[1])

WAVESTEPS = 49 #wavelength samples
WAVEDELTA = 0.1 #wavelength spacing of array

if WAVESTEPS % 2 == 0:
    CENWAV = (WAVESTEPS // 2)-1 #(probably avoid even sized wav arrays for now..)
else:
    CENWAV = WAVESTEPS // 2

SPECTRA_AABB = ivec4(0, VERTICAL_PAD, SPEC_WIDTH, VIEWER_HEIGHT+VERTICAL_PAD)
PLOT_AABB = ivec4(VIEWER_AABB[2], VIEWER_AABB[1], VIEWER_AABB[2]+RIGHT_PAD, (VERTICAL_PAD+(VIEWER_HEIGHT//2)))
SLIT_RES = CAM_HEIGHT

BLUR_KERNEL_SIZE = 31

SPEC_PLOT = True
